name: Java CI run tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 15
        uses: actions/setup-java@v4
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Run tests
        run: mvn test
